### ISSUE TITLE
[Emhancement] 一鍵自動方案

### ISSUE THREAD

**Issue by ingrid-z** [Bighsueh/OverwatchAvoidKoreaServer#1]
開啟Block IP 後，隨後程式碼launch overwach.exe，monitor overwatch.exe，沒有在task manager則自動關閉。

**Comment by Bighsueh** [comment]
個人不是很想要直接關係到遊戲本身，怕會有太多可以解釋的空間。
但是這邊還是歡迎可以提出或實踐自己的想法。

**Comment by ingrid-z** [comment]
> 個人不是很想要直接關係到遊戲本身，怕會有太多可以解釋的空間。 但是這邊還是歡迎可以提出或實踐自己的想法。

我沒有注意看Overwatch的ToS，但這應該沒有修改遊戲本體的問題。
您隨意吧。 😄
